server:
  port: 33816
spring:
  application:
    name: mindtrace-mastery
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: mindtrace-mastery

  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mindtrace-mastery?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 2004131phy123

  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
    