server:
  port: 32196
spring:
  application:
    name: mindtrace-core
  cloud:
    nacos:
      server-addr: localhost:8848
#      server-addr: 39.108.71.232:8848
      discovery:
        service: mindtrace-core
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mindtrace_core?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 2004131phy123
