nacos:
  config:
    server-addr: ${SERVER_HOST}

logging:
  file:
    name: ${MINDTRACE_LOG_DIR}/gateway.log

spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 1521324702@qq.com
    password: keesdkevvpzoibje
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true