server:
  port: 34443
spring:
  application:
    name: mindtrace-gateway
  main:
    web-application-type: reactive
  cloud:
    # nacos
    nacos:
      server-addr: localhost:8848
      discovery:
        service: mindtrace-gateway
    # spring cloud gateway
    gateway:
      routes:
        - id: core
          uri: lb://mindtrace-core
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
        - id: enhancer
          uri: lb://mindtrace-enhancer
          predicates:
            - Path=/enhancer/**
          filters:
            - StripPrefix=1
        - id: tracing
          uri: lb://mindtrace-tracing
          predicates:
            - Path=/tracing/**
          filters:
            - StripPrefix=1
        - id: mastery
          uri: lb://mindtrace-mastery
          predicates:
            - Path=/mastery/**
          filters:
            - StripPrefix=1
        - id: path-optimizer
          uri: lb://mindtrace-path-optimizer
          predicates:
            - Path=/path-optimizer/**
          filters:
            - StripPrefix=1
        - id: recommend
          uri: lb://mindtrace-recommend
          predicates:
            - Path=/recommend/**
          filters:
            - StripPrefix=1
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mindtrace_security?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 2004131phy123

  #  redis
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100

# sa-token安全框架
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false